// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xstream2mem.h"

extern XStream2mem_Config XStream2mem_ConfigTable[];

XStream2mem_Config *XStream2mem_LookupConfig(u16 DeviceId) {
	XStream2mem_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSTREAM2MEM_NUM_INSTANCES; Index++) {
		if (XStream2mem_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XStream2mem_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XStream2mem_Initialize(XStream2mem *InstancePtr, u16 DeviceId) {
	XStream2mem_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XStream2mem_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XStream2mem_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

