// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dataflow_in_loop (
        w,
        m_axi_pMemPort_AWVALID,
        m_axi_pMemPort_AWREADY,
        m_axi_pMemPort_AWADDR,
        m_axi_pMemPort_AWID,
        m_axi_pMemPort_AWLEN,
        m_axi_pMemPort_AWSIZE,
        m_axi_pMemPort_AWBURST,
        m_axi_pMemPort_AWLOCK,
        m_axi_pMemPort_AWCACHE,
        m_axi_pMemPort_AWPROT,
        m_axi_pMemPort_AWQOS,
        m_axi_pMemPort_AWREGION,
        m_axi_pMemPort_AWUSER,
        m_axi_pMemPort_WVALID,
        m_axi_pMemPort_WREADY,
        m_axi_pMemPort_WDATA,
        m_axi_pMemPort_WSTRB,
        m_axi_pMemPort_WLAST,
        m_axi_pMemPort_WID,
        m_axi_pMemPort_WUSER,
        m_axi_pMemPort_ARVALID,
        m_axi_pMemPort_ARREADY,
        m_axi_pMemPort_ARADDR,
        m_axi_pMemPort_ARID,
        m_axi_pMemPort_ARLEN,
        m_axi_pMemPort_ARSIZE,
        m_axi_pMemPort_ARBURST,
        m_axi_pMemPort_ARLOCK,
        m_axi_pMemPort_ARCACHE,
        m_axi_pMemPort_ARPROT,
        m_axi_pMemPort_ARQOS,
        m_axi_pMemPort_ARREGION,
        m_axi_pMemPort_ARUSER,
        m_axi_pMemPort_RVALID,
        m_axi_pMemPort_RREADY,
        m_axi_pMemPort_RDATA,
        m_axi_pMemPort_RLAST,
        m_axi_pMemPort_RID,
        m_axi_pMemPort_RUSER,
        m_axi_pMemPort_RRESP,
        m_axi_pMemPort_BVALID,
        m_axi_pMemPort_BREADY,
        m_axi_pMemPort_BRESP,
        m_axi_pMemPort_BID,
        m_axi_pMemPort_BUSER,
        row,
        p_read,
        p_read1,
        img_data_stream_0_V_din,
        img_data_stream_0_V_full_n,
        img_data_stream_0_V_write,
        img_data_stream_1_V_din,
        img_data_stream_1_V_full_n,
        img_data_stream_1_V_write,
        img_data_stream_2_V_din,
        img_data_stream_2_V_full_n,
        img_data_stream_2_V_write,
        index,
        baseAddr_address0,
        baseAddr_ce0,
        baseAddr_d0,
        baseAddr_q0,
        baseAddr_we0,
        ap_clk,
        ap_rst,
        w_ap_vld,
        row_ap_vld,
        p_read_ap_vld,
        p_read1_ap_vld,
        index_ap_vld,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] w;
output   m_axi_pMemPort_AWVALID;
input   m_axi_pMemPort_AWREADY;
output  [31:0] m_axi_pMemPort_AWADDR;
output  [0:0] m_axi_pMemPort_AWID;
output  [31:0] m_axi_pMemPort_AWLEN;
output  [2:0] m_axi_pMemPort_AWSIZE;
output  [1:0] m_axi_pMemPort_AWBURST;
output  [1:0] m_axi_pMemPort_AWLOCK;
output  [3:0] m_axi_pMemPort_AWCACHE;
output  [2:0] m_axi_pMemPort_AWPROT;
output  [3:0] m_axi_pMemPort_AWQOS;
output  [3:0] m_axi_pMemPort_AWREGION;
output  [0:0] m_axi_pMemPort_AWUSER;
output   m_axi_pMemPort_WVALID;
input   m_axi_pMemPort_WREADY;
output  [31:0] m_axi_pMemPort_WDATA;
output  [3:0] m_axi_pMemPort_WSTRB;
output   m_axi_pMemPort_WLAST;
output  [0:0] m_axi_pMemPort_WID;
output  [0:0] m_axi_pMemPort_WUSER;
output   m_axi_pMemPort_ARVALID;
input   m_axi_pMemPort_ARREADY;
output  [31:0] m_axi_pMemPort_ARADDR;
output  [0:0] m_axi_pMemPort_ARID;
output  [31:0] m_axi_pMemPort_ARLEN;
output  [2:0] m_axi_pMemPort_ARSIZE;
output  [1:0] m_axi_pMemPort_ARBURST;
output  [1:0] m_axi_pMemPort_ARLOCK;
output  [3:0] m_axi_pMemPort_ARCACHE;
output  [2:0] m_axi_pMemPort_ARPROT;
output  [3:0] m_axi_pMemPort_ARQOS;
output  [3:0] m_axi_pMemPort_ARREGION;
output  [0:0] m_axi_pMemPort_ARUSER;
input   m_axi_pMemPort_RVALID;
output   m_axi_pMemPort_RREADY;
input  [31:0] m_axi_pMemPort_RDATA;
input   m_axi_pMemPort_RLAST;
input  [0:0] m_axi_pMemPort_RID;
input  [0:0] m_axi_pMemPort_RUSER;
input  [1:0] m_axi_pMemPort_RRESP;
input   m_axi_pMemPort_BVALID;
output   m_axi_pMemPort_BREADY;
input  [1:0] m_axi_pMemPort_BRESP;
input  [0:0] m_axi_pMemPort_BID;
input  [0:0] m_axi_pMemPort_BUSER;
input  [30:0] row;
input  [31:0] p_read;
input  [31:0] p_read1;
output  [7:0] img_data_stream_0_V_din;
input   img_data_stream_0_V_full_n;
output   img_data_stream_0_V_write;
output  [7:0] img_data_stream_1_V_din;
input   img_data_stream_1_V_full_n;
output   img_data_stream_1_V_write;
output  [7:0] img_data_stream_2_V_din;
input   img_data_stream_2_V_full_n;
output   img_data_stream_2_V_write;
input  [31:0] index;
output  [1:0] baseAddr_address0;
output   baseAddr_ce0;
output  [31:0] baseAddr_d0;
input  [31:0] baseAddr_q0;
output   baseAddr_we0;
input   ap_clk;
input   ap_rst;
input   w_ap_vld;
input   row_ap_vld;
input   p_read_ap_vld;
input   p_read1_ap_vld;
input   index_ap_vld;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    readmem_U0_ap_start;
wire    readmem_U0_ap_done;
wire    readmem_U0_ap_continue;
wire    readmem_U0_ap_idle;
wire    readmem_U0_ap_ready;
wire    readmem_U0_start_out;
wire    readmem_U0_start_write;
wire    readmem_U0_m_axi_pMemPort_AWVALID;
wire   [31:0] readmem_U0_m_axi_pMemPort_AWADDR;
wire   [0:0] readmem_U0_m_axi_pMemPort_AWID;
wire   [31:0] readmem_U0_m_axi_pMemPort_AWLEN;
wire   [2:0] readmem_U0_m_axi_pMemPort_AWSIZE;
wire   [1:0] readmem_U0_m_axi_pMemPort_AWBURST;
wire   [1:0] readmem_U0_m_axi_pMemPort_AWLOCK;
wire   [3:0] readmem_U0_m_axi_pMemPort_AWCACHE;
wire   [2:0] readmem_U0_m_axi_pMemPort_AWPROT;
wire   [3:0] readmem_U0_m_axi_pMemPort_AWQOS;
wire   [3:0] readmem_U0_m_axi_pMemPort_AWREGION;
wire   [0:0] readmem_U0_m_axi_pMemPort_AWUSER;
wire    readmem_U0_m_axi_pMemPort_WVALID;
wire   [31:0] readmem_U0_m_axi_pMemPort_WDATA;
wire   [3:0] readmem_U0_m_axi_pMemPort_WSTRB;
wire    readmem_U0_m_axi_pMemPort_WLAST;
wire   [0:0] readmem_U0_m_axi_pMemPort_WID;
wire   [0:0] readmem_U0_m_axi_pMemPort_WUSER;
wire    readmem_U0_m_axi_pMemPort_ARVALID;
wire   [31:0] readmem_U0_m_axi_pMemPort_ARADDR;
wire   [0:0] readmem_U0_m_axi_pMemPort_ARID;
wire   [31:0] readmem_U0_m_axi_pMemPort_ARLEN;
wire   [2:0] readmem_U0_m_axi_pMemPort_ARSIZE;
wire   [1:0] readmem_U0_m_axi_pMemPort_ARBURST;
wire   [1:0] readmem_U0_m_axi_pMemPort_ARLOCK;
wire   [3:0] readmem_U0_m_axi_pMemPort_ARCACHE;
wire   [2:0] readmem_U0_m_axi_pMemPort_ARPROT;
wire   [3:0] readmem_U0_m_axi_pMemPort_ARQOS;
wire   [3:0] readmem_U0_m_axi_pMemPort_ARREGION;
wire   [0:0] readmem_U0_m_axi_pMemPort_ARUSER;
wire    readmem_U0_m_axi_pMemPort_RREADY;
wire    readmem_U0_m_axi_pMemPort_BREADY;
wire   [31:0] readmem_U0_to_r_din;
wire    readmem_U0_to_r_write;
wire   [31:0] readmem_U0_img_cols_V_out_din;
wire    readmem_U0_img_cols_V_out_write;
wire   [1:0] readmem_U0_baseAddr_address0;
wire    readmem_U0_baseAddr_ce0;
wire    Loop_0_proc_U0_ap_start;
wire    Loop_0_proc_U0_ap_done;
wire    Loop_0_proc_U0_ap_continue;
wire    Loop_0_proc_U0_ap_idle;
wire    Loop_0_proc_U0_ap_ready;
wire    Loop_0_proc_U0_img_cols_V_read;
wire    Loop_0_proc_U0_cacheBuff1_i_read;
wire   [7:0] Loop_0_proc_U0_img_data_stream_0_V_din;
wire    Loop_0_proc_U0_img_data_stream_0_V_write;
wire   [7:0] Loop_0_proc_U0_img_data_stream_1_V_din;
wire    Loop_0_proc_U0_img_data_stream_1_V_write;
wire   [7:0] Loop_0_proc_U0_img_data_stream_2_V_din;
wire    Loop_0_proc_U0_img_data_stream_2_V_write;
wire    ap_sync_continue;
wire    cacheBuff_full_n;
wire   [31:0] cacheBuff_dout;
wire    cacheBuff_empty_n;
wire    img_cols_V_c_full_n;
wire   [31:0] img_cols_V_c_dout;
wire    img_cols_V_c_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_Loop_0_proc_U0_din;
wire    start_for_Loop_0_proc_U0_full_n;
wire   [0:0] start_for_Loop_0_proc_U0_dout;
wire    start_for_Loop_0_proc_U0_empty_n;
wire    Loop_0_proc_U0_start_full_n;
wire    Loop_0_proc_U0_start_write;

readmem readmem_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(readmem_U0_ap_start),
    .start_full_n(start_for_Loop_0_proc_U0_full_n),
    .ap_done(readmem_U0_ap_done),
    .ap_continue(readmem_U0_ap_continue),
    .ap_idle(readmem_U0_ap_idle),
    .ap_ready(readmem_U0_ap_ready),
    .start_out(readmem_U0_start_out),
    .start_write(readmem_U0_start_write),
    .m_axi_pMemPort_AWVALID(readmem_U0_m_axi_pMemPort_AWVALID),
    .m_axi_pMemPort_AWREADY(1'b0),
    .m_axi_pMemPort_AWADDR(readmem_U0_m_axi_pMemPort_AWADDR),
    .m_axi_pMemPort_AWID(readmem_U0_m_axi_pMemPort_AWID),
    .m_axi_pMemPort_AWLEN(readmem_U0_m_axi_pMemPort_AWLEN),
    .m_axi_pMemPort_AWSIZE(readmem_U0_m_axi_pMemPort_AWSIZE),
    .m_axi_pMemPort_AWBURST(readmem_U0_m_axi_pMemPort_AWBURST),
    .m_axi_pMemPort_AWLOCK(readmem_U0_m_axi_pMemPort_AWLOCK),
    .m_axi_pMemPort_AWCACHE(readmem_U0_m_axi_pMemPort_AWCACHE),
    .m_axi_pMemPort_AWPROT(readmem_U0_m_axi_pMemPort_AWPROT),
    .m_axi_pMemPort_AWQOS(readmem_U0_m_axi_pMemPort_AWQOS),
    .m_axi_pMemPort_AWREGION(readmem_U0_m_axi_pMemPort_AWREGION),
    .m_axi_pMemPort_AWUSER(readmem_U0_m_axi_pMemPort_AWUSER),
    .m_axi_pMemPort_WVALID(readmem_U0_m_axi_pMemPort_WVALID),
    .m_axi_pMemPort_WREADY(1'b0),
    .m_axi_pMemPort_WDATA(readmem_U0_m_axi_pMemPort_WDATA),
    .m_axi_pMemPort_WSTRB(readmem_U0_m_axi_pMemPort_WSTRB),
    .m_axi_pMemPort_WLAST(readmem_U0_m_axi_pMemPort_WLAST),
    .m_axi_pMemPort_WID(readmem_U0_m_axi_pMemPort_WID),
    .m_axi_pMemPort_WUSER(readmem_U0_m_axi_pMemPort_WUSER),
    .m_axi_pMemPort_ARVALID(readmem_U0_m_axi_pMemPort_ARVALID),
    .m_axi_pMemPort_ARREADY(m_axi_pMemPort_ARREADY),
    .m_axi_pMemPort_ARADDR(readmem_U0_m_axi_pMemPort_ARADDR),
    .m_axi_pMemPort_ARID(readmem_U0_m_axi_pMemPort_ARID),
    .m_axi_pMemPort_ARLEN(readmem_U0_m_axi_pMemPort_ARLEN),
    .m_axi_pMemPort_ARSIZE(readmem_U0_m_axi_pMemPort_ARSIZE),
    .m_axi_pMemPort_ARBURST(readmem_U0_m_axi_pMemPort_ARBURST),
    .m_axi_pMemPort_ARLOCK(readmem_U0_m_axi_pMemPort_ARLOCK),
    .m_axi_pMemPort_ARCACHE(readmem_U0_m_axi_pMemPort_ARCACHE),
    .m_axi_pMemPort_ARPROT(readmem_U0_m_axi_pMemPort_ARPROT),
    .m_axi_pMemPort_ARQOS(readmem_U0_m_axi_pMemPort_ARQOS),
    .m_axi_pMemPort_ARREGION(readmem_U0_m_axi_pMemPort_ARREGION),
    .m_axi_pMemPort_ARUSER(readmem_U0_m_axi_pMemPort_ARUSER),
    .m_axi_pMemPort_RVALID(m_axi_pMemPort_RVALID),
    .m_axi_pMemPort_RREADY(readmem_U0_m_axi_pMemPort_RREADY),
    .m_axi_pMemPort_RDATA(m_axi_pMemPort_RDATA),
    .m_axi_pMemPort_RLAST(m_axi_pMemPort_RLAST),
    .m_axi_pMemPort_RID(m_axi_pMemPort_RID),
    .m_axi_pMemPort_RUSER(m_axi_pMemPort_RUSER),
    .m_axi_pMemPort_RRESP(m_axi_pMemPort_RRESP),
    .m_axi_pMemPort_BVALID(1'b0),
    .m_axi_pMemPort_BREADY(readmem_U0_m_axi_pMemPort_BREADY),
    .m_axi_pMemPort_BRESP(2'd0),
    .m_axi_pMemPort_BID(1'd0),
    .m_axi_pMemPort_BUSER(1'd0),
    .w(w),
    .row(row),
    .rows(p_read),
    .to_r_din(readmem_U0_to_r_din),
    .to_r_full_n(cacheBuff_full_n),
    .to_r_write(readmem_U0_to_r_write),
    .p_read1(p_read1),
    .img_cols_V_out_din(readmem_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(img_cols_V_c_full_n),
    .img_cols_V_out_write(readmem_U0_img_cols_V_out_write),
    .index(index),
    .baseAddr_address0(readmem_U0_baseAddr_address0),
    .baseAddr_ce0(readmem_U0_baseAddr_ce0),
    .baseAddr_q0(baseAddr_q0)
);

Loop_0_proc Loop_0_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_0_proc_U0_ap_start),
    .ap_done(Loop_0_proc_U0_ap_done),
    .ap_continue(Loop_0_proc_U0_ap_continue),
    .ap_idle(Loop_0_proc_U0_ap_idle),
    .ap_ready(Loop_0_proc_U0_ap_ready),
    .img_cols_V_dout(img_cols_V_c_dout),
    .img_cols_V_empty_n(img_cols_V_c_empty_n),
    .img_cols_V_read(Loop_0_proc_U0_img_cols_V_read),
    .cacheBuff1_i_dout(cacheBuff_dout),
    .cacheBuff1_i_empty_n(cacheBuff_empty_n),
    .cacheBuff1_i_read(Loop_0_proc_U0_cacheBuff1_i_read),
    .img_data_stream_0_V_din(Loop_0_proc_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(img_data_stream_0_V_full_n),
    .img_data_stream_0_V_write(Loop_0_proc_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(Loop_0_proc_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(img_data_stream_1_V_full_n),
    .img_data_stream_1_V_write(Loop_0_proc_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(Loop_0_proc_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(img_data_stream_2_V_full_n),
    .img_data_stream_2_V_write(Loop_0_proc_U0_img_data_stream_2_V_write)
);

fifo_w32_d3840_A cacheBuff_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readmem_U0_to_r_din),
    .if_full_n(cacheBuff_full_n),
    .if_write(readmem_U0_to_r_write),
    .if_dout(cacheBuff_dout),
    .if_empty_n(cacheBuff_empty_n),
    .if_read(Loop_0_proc_U0_cacheBuff1_i_read)
);

fifo_w32_d1_A img_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readmem_U0_img_cols_V_out_din),
    .if_full_n(img_cols_V_c_full_n),
    .if_write(readmem_U0_img_cols_V_out_write),
    .if_dout(img_cols_V_c_dout),
    .if_empty_n(img_cols_V_c_empty_n),
    .if_read(Loop_0_proc_U0_img_cols_V_read)
);

start_for_Loop_0_cud start_for_Loop_0_cud_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_0_proc_U0_din),
    .if_full_n(start_for_Loop_0_proc_U0_full_n),
    .if_write(readmem_U0_start_write),
    .if_dout(start_for_Loop_0_proc_U0_dout),
    .if_empty_n(start_for_Loop_0_proc_U0_empty_n),
    .if_read(Loop_0_proc_U0_ap_ready)
);

assign Loop_0_proc_U0_ap_continue = ap_continue;

assign Loop_0_proc_U0_ap_start = start_for_Loop_0_proc_U0_empty_n;

assign Loop_0_proc_U0_start_full_n = 1'b1;

assign Loop_0_proc_U0_start_write = 1'b0;

assign ap_done = Loop_0_proc_U0_ap_done;

assign ap_idle = (readmem_U0_ap_idle & Loop_0_proc_U0_ap_idle);

assign ap_ready = readmem_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = Loop_0_proc_U0_ap_done;

assign ap_sync_ready = readmem_U0_ap_ready;

assign baseAddr_address0 = readmem_U0_baseAddr_address0;

assign baseAddr_ce0 = readmem_U0_baseAddr_ce0;

assign baseAddr_d0 = 32'd0;

assign baseAddr_we0 = 1'b0;

assign img_data_stream_0_V_din = Loop_0_proc_U0_img_data_stream_0_V_din;

assign img_data_stream_0_V_write = Loop_0_proc_U0_img_data_stream_0_V_write;

assign img_data_stream_1_V_din = Loop_0_proc_U0_img_data_stream_1_V_din;

assign img_data_stream_1_V_write = Loop_0_proc_U0_img_data_stream_1_V_write;

assign img_data_stream_2_V_din = Loop_0_proc_U0_img_data_stream_2_V_din;

assign img_data_stream_2_V_write = Loop_0_proc_U0_img_data_stream_2_V_write;

assign m_axi_pMemPort_ARADDR = readmem_U0_m_axi_pMemPort_ARADDR;

assign m_axi_pMemPort_ARBURST = readmem_U0_m_axi_pMemPort_ARBURST;

assign m_axi_pMemPort_ARCACHE = readmem_U0_m_axi_pMemPort_ARCACHE;

assign m_axi_pMemPort_ARID = readmem_U0_m_axi_pMemPort_ARID;

assign m_axi_pMemPort_ARLEN = readmem_U0_m_axi_pMemPort_ARLEN;

assign m_axi_pMemPort_ARLOCK = readmem_U0_m_axi_pMemPort_ARLOCK;

assign m_axi_pMemPort_ARPROT = readmem_U0_m_axi_pMemPort_ARPROT;

assign m_axi_pMemPort_ARQOS = readmem_U0_m_axi_pMemPort_ARQOS;

assign m_axi_pMemPort_ARREGION = readmem_U0_m_axi_pMemPort_ARREGION;

assign m_axi_pMemPort_ARSIZE = readmem_U0_m_axi_pMemPort_ARSIZE;

assign m_axi_pMemPort_ARUSER = readmem_U0_m_axi_pMemPort_ARUSER;

assign m_axi_pMemPort_ARVALID = readmem_U0_m_axi_pMemPort_ARVALID;

assign m_axi_pMemPort_AWADDR = 32'd0;

assign m_axi_pMemPort_AWBURST = 2'd0;

assign m_axi_pMemPort_AWCACHE = 4'd0;

assign m_axi_pMemPort_AWID = 1'd0;

assign m_axi_pMemPort_AWLEN = 32'd0;

assign m_axi_pMemPort_AWLOCK = 2'd0;

assign m_axi_pMemPort_AWPROT = 3'd0;

assign m_axi_pMemPort_AWQOS = 4'd0;

assign m_axi_pMemPort_AWREGION = 4'd0;

assign m_axi_pMemPort_AWSIZE = 3'd0;

assign m_axi_pMemPort_AWUSER = 1'd0;

assign m_axi_pMemPort_AWVALID = 1'b0;

assign m_axi_pMemPort_BREADY = 1'b0;

assign m_axi_pMemPort_RREADY = readmem_U0_m_axi_pMemPort_RREADY;

assign m_axi_pMemPort_WDATA = 32'd0;

assign m_axi_pMemPort_WID = 1'd0;

assign m_axi_pMemPort_WLAST = 1'b0;

assign m_axi_pMemPort_WSTRB = 4'd0;

assign m_axi_pMemPort_WUSER = 1'd0;

assign m_axi_pMemPort_WVALID = 1'b0;

assign readmem_U0_ap_continue = 1'b1;

assign readmem_U0_ap_start = ap_start;

assign start_for_Loop_0_proc_U0_din = 1'b1;

endmodule //dataflow_in_loop
