-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Loop_0_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_cols_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    img_cols_V_empty_n : IN STD_LOGIC;
    img_cols_V_read : OUT STD_LOGIC;
    cacheBuff1_i_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    cacheBuff1_i_empty_n : IN STD_LOGIC;
    cacheBuff1_i_read : OUT STD_LOGIC;
    img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_0_V_full_n : IN STD_LOGIC;
    img_data_stream_0_V_write : OUT STD_LOGIC;
    img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_1_V_full_n : IN STD_LOGIC;
    img_data_stream_1_V_write : OUT STD_LOGIC;
    img_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_2_V_full_n : IN STD_LOGIC;
    img_data_stream_2_V_write : OUT STD_LOGIC );
end;


architecture behav of Loop_0_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_FFFFFFFD : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111101";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal img_cols_V_blk_n : STD_LOGIC;
    signal cacheBuff1_i_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_20_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal img_data_stream_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal img_data_stream_1_V_blk_n : STD_LOGIC;
    signal img_data_stream_2_V_blk_n : STD_LOGIC;
    signal reg_209 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal ap_block_state4 : BOOLEAN;
    signal ap_block_state5 : BOOLEAN;
    signal reg_216 : STD_LOGIC_VECTOR (7 downto 0);
    signal img_cols_V_read_reg_323 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal tmp_19_fu_289_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_reg_330 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal col_fu_307_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal col_reg_338 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_reg_343 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_i_i_reg_165 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state6 : BOOLEAN;
    signal tmp_21_fu_302_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_313_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_318_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal img_cols_V_load_op_o_fu_229_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_neg_fu_242_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_lshr_fu_247_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_11_fu_234_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t_fu_257_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_16_fu_263_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_fu_222_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_273_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_18_fu_281_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    col_i_i_reg_165_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                col_i_i_reg_165 <= col_reg_338;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                col_i_i_reg_165 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                col_reg_338 <= col_fu_307_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((img_cols_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                img_cols_V_read_reg_323 <= img_cols_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then
                reg_209 <= cacheBuff1_i_dout(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then
                reg_216 <= cacheBuff1_i_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    tmp_19_reg_330(31 downto 2) <= tmp_19_fu_289_p3(31 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                tmp_25_reg_343 <= cacheBuff1_i_dout(15 downto 8);
            end if;
        end if;
    end process;
    tmp_19_reg_330(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, img_cols_V_empty_n, cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((img_cols_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, img_cols_V_empty_n)
    begin
                ap_block_state1 <= ((img_cols_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state3_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, tmp_20_fu_297_p2)
    begin
                ap_block_state3 <= (((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state4_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n)
    begin
                ap_block_state4 <= ((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n)
    begin
                ap_block_state5 <= ((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0));
    end process;


    ap_block_state6_assign_proc : process(img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n)
    begin
                ap_block_state6 <= ((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2)
    begin
        if ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2)
    begin
        if ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    cacheBuff1_i_blk_n_assign_proc : process(cacheBuff1_i_empty_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            cacheBuff1_i_blk_n <= cacheBuff1_i_empty_n;
        else 
            cacheBuff1_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    cacheBuff1_i_read_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            cacheBuff1_i_read <= ap_const_logic_1;
        else 
            cacheBuff1_i_read <= ap_const_logic_0;
        end if; 
    end process;

    col_fu_307_p2 <= std_logic_vector(unsigned(ap_const_lv32_4) + unsigned(col_i_i_reg_165));

    img_cols_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, img_cols_V_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_cols_V_blk_n <= img_cols_V_empty_n;
        else 
            img_cols_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_cols_V_load_op_o_fu_229_p2 <= std_logic_vector(unsigned(img_cols_V_read_reg_323) + unsigned(ap_const_lv32_3));

    img_cols_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, img_cols_V_empty_n)
    begin
        if ((not(((img_cols_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_cols_V_read <= ap_const_logic_1;
        else 
            img_cols_V_read <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_0_V_blk_n_assign_proc : process(img_data_stream_0_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            img_data_stream_0_V_blk_n <= img_data_stream_0_V_full_n;
        else 
            img_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_data_stream_0_V_din_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, reg_209, reg_216, tmp_25_reg_343, tmp_21_fu_302_p1)
    begin
        if ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            img_data_stream_0_V_din <= tmp_25_reg_343;
        elsif ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            img_data_stream_0_V_din <= reg_216;
        elsif ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            img_data_stream_0_V_din <= reg_209;
        elsif ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            img_data_stream_0_V_din <= tmp_21_fu_302_p1;
        else 
            img_data_stream_0_V_din <= "XXXXXXXX";
        end if; 
    end process;


    img_data_stream_0_V_write_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            img_data_stream_0_V_write <= ap_const_logic_1;
        else 
            img_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_1_V_blk_n_assign_proc : process(img_data_stream_1_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            img_data_stream_1_V_blk_n <= img_data_stream_1_V_full_n;
        else 
            img_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_data_stream_1_V_din_assign_proc : process(cacheBuff1_i_dout, cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, reg_209, reg_216, tmp_22_fu_313_p1)
    begin
        if ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            img_data_stream_1_V_din <= reg_216;
        elsif ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            img_data_stream_1_V_din <= reg_209;
        elsif ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            img_data_stream_1_V_din <= tmp_22_fu_313_p1;
        elsif ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            img_data_stream_1_V_din <= cacheBuff1_i_dout(15 downto 8);
        else 
            img_data_stream_1_V_din <= "XXXXXXXX";
        end if; 
    end process;


    img_data_stream_1_V_write_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            img_data_stream_1_V_write <= ap_const_logic_1;
        else 
            img_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_2_V_blk_n_assign_proc : process(img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            img_data_stream_2_V_blk_n <= img_data_stream_2_V_full_n;
        else 
            img_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_data_stream_2_V_din_assign_proc : process(cacheBuff1_i_dout, cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, reg_209, tmp_23_fu_318_p1)
    begin
        if ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            img_data_stream_2_V_din <= reg_209;
        elsif ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            img_data_stream_2_V_din <= tmp_23_fu_318_p1;
        elsif ((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            img_data_stream_2_V_din <= cacheBuff1_i_dout(15 downto 8);
        elsif ((not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            img_data_stream_2_V_din <= cacheBuff1_i_dout(23 downto 16);
        else 
            img_data_stream_2_V_din <= "XXXXXXXX";
        end if; 
    end process;


    img_data_stream_2_V_write_assign_proc : process(cacheBuff1_i_empty_n, img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_CS_fsm_state3, tmp_20_fu_297_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((img_data_stream_2_V_full_n = ap_const_logic_0) or (img_data_stream_1_V_full_n = ap_const_logic_0) or (img_data_stream_0_V_full_n = ap_const_logic_0) or (cacheBuff1_i_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not((((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_2_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_20_fu_297_p2 = ap_const_lv1_0) and (cacheBuff1_i_empty_n = ap_const_logic_0)))) and (tmp_20_fu_297_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            img_data_stream_2_V_write <= ap_const_logic_1;
        else 
            img_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_lshr_fu_247_p4 <= p_neg_fu_242_p2(31 downto 2);
    p_neg_fu_242_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFD) - signed(img_cols_V_read_reg_323));
    p_neg_t_fu_257_p2 <= std_logic_vector(unsigned(ap_const_lv30_0) - unsigned(p_lshr_fu_247_p4));
    tmp_11_fu_234_p3 <= img_cols_V_load_op_o_fu_229_p2(31 downto 31);
    tmp_16_fu_263_p4 <= img_cols_V_load_op_o_fu_229_p2(31 downto 2);
    tmp_17_fu_273_p3 <= 
        p_neg_t_fu_257_p2 when (tmp_11_fu_234_p3(0) = '1') else 
        tmp_16_fu_263_p4;
    tmp_18_fu_281_p3 <= 
        ap_const_lv30_0 when (tmp_fu_222_p3(0) = '1') else 
        tmp_17_fu_273_p3;
    tmp_19_fu_289_p3 <= (tmp_18_fu_281_p3 & ap_const_lv2_0);
    tmp_20_fu_297_p2 <= "1" when (col_i_i_reg_165 = tmp_19_reg_330) else "0";
    tmp_21_fu_302_p1 <= cacheBuff1_i_dout(8 - 1 downto 0);
    tmp_22_fu_313_p1 <= cacheBuff1_i_dout(8 - 1 downto 0);
    tmp_23_fu_318_p1 <= cacheBuff1_i_dout(8 - 1 downto 0);
    tmp_fu_222_p3 <= img_cols_V_read_reg_323(31 downto 31);
end behav;
