-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mem2stream is
generic (
    C_S_AXI_AXILITES_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_AXILITES_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_PMEMPORT_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_PMEMPORT_ID_WIDTH : INTEGER := 1;
    C_M_AXI_PMEMPORT_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_PMEMPORT_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_PMEMPORT_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_PMEMPORT_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_PMEMPORT_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_PMEMPORT_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_PMEMPORT_TARGET_ADDR : INTEGER := 0;
    C_M_AXI_PMEMPORT_USER_VALUE : INTEGER := 0;
    C_M_AXI_PMEMPORT_PROT_VALUE : INTEGER := 0;
    C_M_AXI_PMEMPORT_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_AXILiteS_AWVALID : IN STD_LOGIC;
    s_axi_AXILiteS_AWREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_WVALID : IN STD_LOGIC;
    s_axi_AXILiteS_WREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH/8-1 downto 0);
    s_axi_AXILiteS_ARVALID : IN STD_LOGIC;
    s_axi_AXILiteS_ARREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_RVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_RREADY : IN STD_LOGIC;
    s_axi_AXILiteS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_AXILiteS_BVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_BREADY : IN STD_LOGIC;
    s_axi_AXILiteS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_pMemPort_AWVALID : OUT STD_LOGIC;
    m_axi_pMemPort_AWREADY : IN STD_LOGIC;
    m_axi_pMemPort_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_ADDR_WIDTH-1 downto 0);
    m_axi_pMemPort_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_ID_WIDTH-1 downto 0);
    m_axi_pMemPort_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_pMemPort_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_pMemPort_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_pMemPort_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_pMemPort_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_pMemPort_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_pMemPort_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_pMemPort_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_pMemPort_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_AWUSER_WIDTH-1 downto 0);
    m_axi_pMemPort_WVALID : OUT STD_LOGIC;
    m_axi_pMemPort_WREADY : IN STD_LOGIC;
    m_axi_pMemPort_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_DATA_WIDTH-1 downto 0);
    m_axi_pMemPort_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_DATA_WIDTH/8-1 downto 0);
    m_axi_pMemPort_WLAST : OUT STD_LOGIC;
    m_axi_pMemPort_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_ID_WIDTH-1 downto 0);
    m_axi_pMemPort_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_WUSER_WIDTH-1 downto 0);
    m_axi_pMemPort_ARVALID : OUT STD_LOGIC;
    m_axi_pMemPort_ARREADY : IN STD_LOGIC;
    m_axi_pMemPort_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_ADDR_WIDTH-1 downto 0);
    m_axi_pMemPort_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_ID_WIDTH-1 downto 0);
    m_axi_pMemPort_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_pMemPort_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_pMemPort_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_pMemPort_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_pMemPort_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_pMemPort_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_pMemPort_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_pMemPort_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_pMemPort_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_ARUSER_WIDTH-1 downto 0);
    m_axi_pMemPort_RVALID : IN STD_LOGIC;
    m_axi_pMemPort_RREADY : OUT STD_LOGIC;
    m_axi_pMemPort_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_DATA_WIDTH-1 downto 0);
    m_axi_pMemPort_RLAST : IN STD_LOGIC;
    m_axi_pMemPort_RID : IN STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_ID_WIDTH-1 downto 0);
    m_axi_pMemPort_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_RUSER_WIDTH-1 downto 0);
    m_axi_pMemPort_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_pMemPort_BVALID : IN STD_LOGIC;
    m_axi_pMemPort_BREADY : OUT STD_LOGIC;
    m_axi_pMemPort_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_pMemPort_BID : IN STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_ID_WIDTH-1 downto 0);
    m_axi_pMemPort_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_PMEMPORT_BUSER_WIDTH-1 downto 0);
    vstream_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    vstream_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    vstream_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    vstream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    vstream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    vstream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    vstream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    indexw : IN STD_LOGIC_VECTOR (31 downto 0);
    indexr : OUT STD_LOGIC_VECTOR (31 downto 0);
    vstream_TVALID : OUT STD_LOGIC;
    vstream_TREADY : IN STD_LOGIC );
end;


architecture behav of mem2stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "mem2stream,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z035ffg676-2,HLS_INPUT_CLOCK=6.666000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.832750,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=12,HLS_SYN_DSP=4,HLS_SYN_FF=2064,HLS_SYN_LUT=3792}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_S_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_S_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_ID_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_M_AXI_AWUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ARUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_WUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_RUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_BUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal rows : STD_LOGIC_VECTOR (31 downto 0);
    signal cols : STD_LOGIC_VECTOR (31 downto 0);
    signal baseAddr_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pMemPort_AWREADY : STD_LOGIC;
    signal pMemPort_WREADY : STD_LOGIC;
    signal pMemPort_ARREADY : STD_LOGIC;
    signal pMemPort_RVALID : STD_LOGIC;
    signal pMemPort_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal pMemPort_RLAST : STD_LOGIC;
    signal pMemPort_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal pMemPort_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal pMemPort_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal pMemPort_BVALID : STD_LOGIC;
    signal pMemPort_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal pMemPort_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal pMemPort_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Block_Mat_exit3_proc_U0_ap_start : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_ap_done : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_ap_continue : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_ap_idle : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_ap_ready : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_img_rows_V_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit3_proc_U0_img_rows_V_out_write : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_img_cols_V_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit3_proc_U0_img_cols_V_out_write : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_indexw_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit3_proc_U0_indexw_out_write : STD_LOGIC;
    signal mem2mat_U0_ap_start : STD_LOGIC;
    signal mem2mat_U0_ap_done : STD_LOGIC;
    signal mem2mat_U0_ap_continue : STD_LOGIC;
    signal mem2mat_U0_ap_idle : STD_LOGIC;
    signal mem2mat_U0_ap_ready : STD_LOGIC;
    signal mem2mat_U0_start_out : STD_LOGIC;
    signal mem2mat_U0_start_write : STD_LOGIC;
    signal mem2mat_U0_img_rows_V_read : STD_LOGIC;
    signal mem2mat_U0_img_cols_V_read : STD_LOGIC;
    signal mem2mat_U0_img_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal mem2mat_U0_img_data_stream_0_V_write : STD_LOGIC;
    signal mem2mat_U0_img_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal mem2mat_U0_img_data_stream_1_V_write : STD_LOGIC;
    signal mem2mat_U0_img_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal mem2mat_U0_img_data_stream_2_V_write : STD_LOGIC;
    signal mem2mat_U0_m_axi_pMemPort_AWVALID : STD_LOGIC;
    signal mem2mat_U0_m_axi_pMemPort_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_WVALID : STD_LOGIC;
    signal mem2mat_U0_m_axi_pMemPort_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_WLAST : STD_LOGIC;
    signal mem2mat_U0_m_axi_pMemPort_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARVALID : STD_LOGIC;
    signal mem2mat_U0_m_axi_pMemPort_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal mem2mat_U0_m_axi_pMemPort_RREADY : STD_LOGIC;
    signal mem2mat_U0_m_axi_pMemPort_BREADY : STD_LOGIC;
    signal mem2mat_U0_w_read : STD_LOGIC;
    signal mem2mat_U0_r : STD_LOGIC_VECTOR (31 downto 0);
    signal mem2mat_U0_r_ap_vld : STD_LOGIC;
    signal mem2mat_U0_img_rows_V_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal mem2mat_U0_img_rows_V_out_write : STD_LOGIC;
    signal mem2mat_U0_img_cols_V_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal mem2mat_U0_img_cols_V_out_write : STD_LOGIC;
    signal mem2mat_U0_baseAddr_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal mem2mat_U0_baseAddr_ce0 : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_start : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_done : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_rows_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_cols_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_0_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_1_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_2_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_vstream_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal Mat2AXIvideo_U0_vstream_TVALID : STD_LOGIC;
    signal Mat2AXIvideo_U0_vstream_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal Mat2AXIvideo_U0_vstream_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal Mat2AXIvideo_U0_vstream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_vstream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_vstream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_vstream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal img_rows_V_c_full_n : STD_LOGIC;
    signal img_rows_V_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_rows_V_c_empty_n : STD_LOGIC;
    signal img_cols_V_c_full_n : STD_LOGIC;
    signal img_cols_V_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_cols_V_c_empty_n : STD_LOGIC;
    signal indexw_c_full_n : STD_LOGIC;
    signal indexw_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal indexw_c_empty_n : STD_LOGIC;
    signal img_data_stream_0_V_full_n : STD_LOGIC;
    signal img_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_data_stream_0_V_empty_n : STD_LOGIC;
    signal img_data_stream_1_V_full_n : STD_LOGIC;
    signal img_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_data_stream_1_V_empty_n : STD_LOGIC;
    signal img_data_stream_2_V_full_n : STD_LOGIC;
    signal img_data_stream_2_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_data_stream_2_V_empty_n : STD_LOGIC;
    signal img_rows_V_c9_full_n : STD_LOGIC;
    signal img_rows_V_c9_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_rows_V_c9_empty_n : STD_LOGIC;
    signal img_cols_V_c10_full_n : STD_LOGIC;
    signal img_cols_V_c10_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_cols_V_c10_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_mem2mat_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_mem2mat_U0_ap_ready : STD_LOGIC;
    signal mem2mat_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_Block_Mat_exit3_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Block_Mat_exit3_proc_U0_ap_ready : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal Block_Mat_exit3_proc_U0_start_full_n : STD_LOGIC;
    signal Block_Mat_exit3_proc_U0_start_write : STD_LOGIC;
    signal start_for_Mat2AXIvideo_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Mat2AXIvideo_U0_full_n : STD_LOGIC;
    signal start_for_Mat2AXIvideo_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Mat2AXIvideo_U0_empty_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_full_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_write : STD_LOGIC;

    component Block_Mat_exit3_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rows : IN STD_LOGIC_VECTOR (31 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        indexw : IN STD_LOGIC_VECTOR (31 downto 0);
        img_rows_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_rows_V_out_full_n : IN STD_LOGIC;
        img_rows_V_out_write : OUT STD_LOGIC;
        img_cols_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_cols_V_out_full_n : IN STD_LOGIC;
        img_cols_V_out_write : OUT STD_LOGIC;
        indexw_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        indexw_out_full_n : IN STD_LOGIC;
        indexw_out_write : OUT STD_LOGIC );
    end component;


    component mem2mat IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        img_rows_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_rows_V_empty_n : IN STD_LOGIC;
        img_rows_V_read : OUT STD_LOGIC;
        img_cols_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_cols_V_empty_n : IN STD_LOGIC;
        img_cols_V_read : OUT STD_LOGIC;
        img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_full_n : IN STD_LOGIC;
        img_data_stream_0_V_write : OUT STD_LOGIC;
        img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_full_n : IN STD_LOGIC;
        img_data_stream_1_V_write : OUT STD_LOGIC;
        img_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_full_n : IN STD_LOGIC;
        img_data_stream_2_V_write : OUT STD_LOGIC;
        m_axi_pMemPort_AWVALID : OUT STD_LOGIC;
        m_axi_pMemPort_AWREADY : IN STD_LOGIC;
        m_axi_pMemPort_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_pMemPort_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_pMemPort_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_pMemPort_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_pMemPort_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_pMemPort_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_pMemPort_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_pMemPort_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_pMemPort_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_pMemPort_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_WVALID : OUT STD_LOGIC;
        m_axi_pMemPort_WREADY : IN STD_LOGIC;
        m_axi_pMemPort_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_pMemPort_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_pMemPort_WLAST : OUT STD_LOGIC;
        m_axi_pMemPort_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_ARVALID : OUT STD_LOGIC;
        m_axi_pMemPort_ARREADY : IN STD_LOGIC;
        m_axi_pMemPort_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_pMemPort_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_pMemPort_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_pMemPort_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_pMemPort_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_pMemPort_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_pMemPort_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_pMemPort_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_pMemPort_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_pMemPort_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_RVALID : IN STD_LOGIC;
        m_axi_pMemPort_RREADY : OUT STD_LOGIC;
        m_axi_pMemPort_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_pMemPort_RLAST : IN STD_LOGIC;
        m_axi_pMemPort_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_pMemPort_BVALID : IN STD_LOGIC;
        m_axi_pMemPort_BREADY : OUT STD_LOGIC;
        m_axi_pMemPort_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_pMemPort_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_pMemPort_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        w_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        w_empty_n : IN STD_LOGIC;
        w_read : OUT STD_LOGIC;
        r : OUT STD_LOGIC_VECTOR (31 downto 0);
        r_ap_vld : OUT STD_LOGIC;
        img_rows_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_rows_V_out_full_n : IN STD_LOGIC;
        img_rows_V_out_write : OUT STD_LOGIC;
        img_cols_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_cols_V_out_full_n : IN STD_LOGIC;
        img_cols_V_out_write : OUT STD_LOGIC;
        baseAddr_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        baseAddr_ce0 : OUT STD_LOGIC;
        baseAddr_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Mat2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_rows_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_rows_V_empty_n : IN STD_LOGIC;
        img_rows_V_read : OUT STD_LOGIC;
        img_cols_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_cols_V_empty_n : IN STD_LOGIC;
        img_cols_V_read : OUT STD_LOGIC;
        img_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_data_stream_0_V_read : OUT STD_LOGIC;
        img_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_data_stream_1_V_read : OUT STD_LOGIC;
        img_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_data_stream_2_V_read : OUT STD_LOGIC;
        vstream_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        vstream_TVALID : OUT STD_LOGIC;
        vstream_TREADY : IN STD_LOGIC;
        vstream_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        vstream_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        vstream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        vstream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        vstream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        vstream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fifo_w32_d1_A_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w8_d1_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_Mat2AXIdEe IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component mem2stream_AXILiteS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        baseAddr_address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        baseAddr_ce0 : IN STD_LOGIC;
        baseAddr_q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mem2stream_pMemPort_m_axi IS
    generic (
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_TARGET_ADDR : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    mem2stream_AXILiteS_s_axi_U : component mem2stream_AXILiteS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXILITES_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXILITES_DATA_WIDTH)
    port map (
        AWVALID => s_axi_AXILiteS_AWVALID,
        AWREADY => s_axi_AXILiteS_AWREADY,
        AWADDR => s_axi_AXILiteS_AWADDR,
        WVALID => s_axi_AXILiteS_WVALID,
        WREADY => s_axi_AXILiteS_WREADY,
        WDATA => s_axi_AXILiteS_WDATA,
        WSTRB => s_axi_AXILiteS_WSTRB,
        ARVALID => s_axi_AXILiteS_ARVALID,
        ARREADY => s_axi_AXILiteS_ARREADY,
        ARADDR => s_axi_AXILiteS_ARADDR,
        RVALID => s_axi_AXILiteS_RVALID,
        RREADY => s_axi_AXILiteS_RREADY,
        RDATA => s_axi_AXILiteS_RDATA,
        RRESP => s_axi_AXILiteS_RRESP,
        BVALID => s_axi_AXILiteS_BVALID,
        BREADY => s_axi_AXILiteS_BREADY,
        BRESP => s_axi_AXILiteS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        rows => rows,
        cols => cols,
        baseAddr_address0 => mem2mat_U0_baseAddr_address0,
        baseAddr_ce0 => mem2mat_U0_baseAddr_ce0,
        baseAddr_q0 => baseAddr_q0);

    mem2stream_pMemPort_m_axi_U : component mem2stream_pMemPort_m_axi
    generic map (
        USER_DW => 32,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_PMEMPORT_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_PMEMPORT_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_PMEMPORT_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_PMEMPORT_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_PMEMPORT_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_PMEMPORT_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_PMEMPORT_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_PMEMPORT_BUSER_WIDTH,
        C_TARGET_ADDR => C_M_AXI_PMEMPORT_TARGET_ADDR,
        C_USER_VALUE => C_M_AXI_PMEMPORT_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_PMEMPORT_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_PMEMPORT_CACHE_VALUE)
    port map (
        AWVALID => m_axi_pMemPort_AWVALID,
        AWREADY => m_axi_pMemPort_AWREADY,
        AWADDR => m_axi_pMemPort_AWADDR,
        AWID => m_axi_pMemPort_AWID,
        AWLEN => m_axi_pMemPort_AWLEN,
        AWSIZE => m_axi_pMemPort_AWSIZE,
        AWBURST => m_axi_pMemPort_AWBURST,
        AWLOCK => m_axi_pMemPort_AWLOCK,
        AWCACHE => m_axi_pMemPort_AWCACHE,
        AWPROT => m_axi_pMemPort_AWPROT,
        AWQOS => m_axi_pMemPort_AWQOS,
        AWREGION => m_axi_pMemPort_AWREGION,
        AWUSER => m_axi_pMemPort_AWUSER,
        WVALID => m_axi_pMemPort_WVALID,
        WREADY => m_axi_pMemPort_WREADY,
        WDATA => m_axi_pMemPort_WDATA,
        WSTRB => m_axi_pMemPort_WSTRB,
        WLAST => m_axi_pMemPort_WLAST,
        WID => m_axi_pMemPort_WID,
        WUSER => m_axi_pMemPort_WUSER,
        ARVALID => m_axi_pMemPort_ARVALID,
        ARREADY => m_axi_pMemPort_ARREADY,
        ARADDR => m_axi_pMemPort_ARADDR,
        ARID => m_axi_pMemPort_ARID,
        ARLEN => m_axi_pMemPort_ARLEN,
        ARSIZE => m_axi_pMemPort_ARSIZE,
        ARBURST => m_axi_pMemPort_ARBURST,
        ARLOCK => m_axi_pMemPort_ARLOCK,
        ARCACHE => m_axi_pMemPort_ARCACHE,
        ARPROT => m_axi_pMemPort_ARPROT,
        ARQOS => m_axi_pMemPort_ARQOS,
        ARREGION => m_axi_pMemPort_ARREGION,
        ARUSER => m_axi_pMemPort_ARUSER,
        RVALID => m_axi_pMemPort_RVALID,
        RREADY => m_axi_pMemPort_RREADY,
        RDATA => m_axi_pMemPort_RDATA,
        RLAST => m_axi_pMemPort_RLAST,
        RID => m_axi_pMemPort_RID,
        RUSER => m_axi_pMemPort_RUSER,
        RRESP => m_axi_pMemPort_RRESP,
        BVALID => m_axi_pMemPort_BVALID,
        BREADY => m_axi_pMemPort_BREADY,
        BRESP => m_axi_pMemPort_BRESP,
        BID => m_axi_pMemPort_BID,
        BUSER => m_axi_pMemPort_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => mem2mat_U0_m_axi_pMemPort_ARVALID,
        I_ARREADY => pMemPort_ARREADY,
        I_ARADDR => mem2mat_U0_m_axi_pMemPort_ARADDR,
        I_ARID => mem2mat_U0_m_axi_pMemPort_ARID,
        I_ARLEN => mem2mat_U0_m_axi_pMemPort_ARLEN,
        I_ARSIZE => mem2mat_U0_m_axi_pMemPort_ARSIZE,
        I_ARLOCK => mem2mat_U0_m_axi_pMemPort_ARLOCK,
        I_ARCACHE => mem2mat_U0_m_axi_pMemPort_ARCACHE,
        I_ARQOS => mem2mat_U0_m_axi_pMemPort_ARQOS,
        I_ARPROT => mem2mat_U0_m_axi_pMemPort_ARPROT,
        I_ARUSER => mem2mat_U0_m_axi_pMemPort_ARUSER,
        I_ARBURST => mem2mat_U0_m_axi_pMemPort_ARBURST,
        I_ARREGION => mem2mat_U0_m_axi_pMemPort_ARREGION,
        I_RVALID => pMemPort_RVALID,
        I_RREADY => mem2mat_U0_m_axi_pMemPort_RREADY,
        I_RDATA => pMemPort_RDATA,
        I_RID => pMemPort_RID,
        I_RUSER => pMemPort_RUSER,
        I_RRESP => pMemPort_RRESP,
        I_RLAST => pMemPort_RLAST,
        I_AWVALID => ap_const_logic_0,
        I_AWREADY => pMemPort_AWREADY,
        I_AWADDR => ap_const_lv32_0,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_0,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => ap_const_logic_0,
        I_WREADY => pMemPort_WREADY,
        I_WDATA => ap_const_lv32_0,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv4_0,
        I_BVALID => pMemPort_BVALID,
        I_BREADY => ap_const_logic_0,
        I_BRESP => pMemPort_BRESP,
        I_BID => pMemPort_BID,
        I_BUSER => pMemPort_BUSER);

    Block_Mat_exit3_proc_U0 : component Block_Mat_exit3_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_Mat_exit3_proc_U0_ap_start,
        ap_done => Block_Mat_exit3_proc_U0_ap_done,
        ap_continue => Block_Mat_exit3_proc_U0_ap_continue,
        ap_idle => Block_Mat_exit3_proc_U0_ap_idle,
        ap_ready => Block_Mat_exit3_proc_U0_ap_ready,
        rows => rows,
        cols => cols,
        indexw => indexw,
        img_rows_V_out_din => Block_Mat_exit3_proc_U0_img_rows_V_out_din,
        img_rows_V_out_full_n => img_rows_V_c_full_n,
        img_rows_V_out_write => Block_Mat_exit3_proc_U0_img_rows_V_out_write,
        img_cols_V_out_din => Block_Mat_exit3_proc_U0_img_cols_V_out_din,
        img_cols_V_out_full_n => img_cols_V_c_full_n,
        img_cols_V_out_write => Block_Mat_exit3_proc_U0_img_cols_V_out_write,
        indexw_out_din => Block_Mat_exit3_proc_U0_indexw_out_din,
        indexw_out_full_n => indexw_c_full_n,
        indexw_out_write => Block_Mat_exit3_proc_U0_indexw_out_write);

    mem2mat_U0 : component mem2mat
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => mem2mat_U0_ap_start,
        start_full_n => start_for_Mat2AXIvideo_U0_full_n,
        ap_done => mem2mat_U0_ap_done,
        ap_continue => mem2mat_U0_ap_continue,
        ap_idle => mem2mat_U0_ap_idle,
        ap_ready => mem2mat_U0_ap_ready,
        start_out => mem2mat_U0_start_out,
        start_write => mem2mat_U0_start_write,
        img_rows_V_dout => img_rows_V_c_dout,
        img_rows_V_empty_n => img_rows_V_c_empty_n,
        img_rows_V_read => mem2mat_U0_img_rows_V_read,
        img_cols_V_dout => img_cols_V_c_dout,
        img_cols_V_empty_n => img_cols_V_c_empty_n,
        img_cols_V_read => mem2mat_U0_img_cols_V_read,
        img_data_stream_0_V_din => mem2mat_U0_img_data_stream_0_V_din,
        img_data_stream_0_V_full_n => img_data_stream_0_V_full_n,
        img_data_stream_0_V_write => mem2mat_U0_img_data_stream_0_V_write,
        img_data_stream_1_V_din => mem2mat_U0_img_data_stream_1_V_din,
        img_data_stream_1_V_full_n => img_data_stream_1_V_full_n,
        img_data_stream_1_V_write => mem2mat_U0_img_data_stream_1_V_write,
        img_data_stream_2_V_din => mem2mat_U0_img_data_stream_2_V_din,
        img_data_stream_2_V_full_n => img_data_stream_2_V_full_n,
        img_data_stream_2_V_write => mem2mat_U0_img_data_stream_2_V_write,
        m_axi_pMemPort_AWVALID => mem2mat_U0_m_axi_pMemPort_AWVALID,
        m_axi_pMemPort_AWREADY => ap_const_logic_0,
        m_axi_pMemPort_AWADDR => mem2mat_U0_m_axi_pMemPort_AWADDR,
        m_axi_pMemPort_AWID => mem2mat_U0_m_axi_pMemPort_AWID,
        m_axi_pMemPort_AWLEN => mem2mat_U0_m_axi_pMemPort_AWLEN,
        m_axi_pMemPort_AWSIZE => mem2mat_U0_m_axi_pMemPort_AWSIZE,
        m_axi_pMemPort_AWBURST => mem2mat_U0_m_axi_pMemPort_AWBURST,
        m_axi_pMemPort_AWLOCK => mem2mat_U0_m_axi_pMemPort_AWLOCK,
        m_axi_pMemPort_AWCACHE => mem2mat_U0_m_axi_pMemPort_AWCACHE,
        m_axi_pMemPort_AWPROT => mem2mat_U0_m_axi_pMemPort_AWPROT,
        m_axi_pMemPort_AWQOS => mem2mat_U0_m_axi_pMemPort_AWQOS,
        m_axi_pMemPort_AWREGION => mem2mat_U0_m_axi_pMemPort_AWREGION,
        m_axi_pMemPort_AWUSER => mem2mat_U0_m_axi_pMemPort_AWUSER,
        m_axi_pMemPort_WVALID => mem2mat_U0_m_axi_pMemPort_WVALID,
        m_axi_pMemPort_WREADY => ap_const_logic_0,
        m_axi_pMemPort_WDATA => mem2mat_U0_m_axi_pMemPort_WDATA,
        m_axi_pMemPort_WSTRB => mem2mat_U0_m_axi_pMemPort_WSTRB,
        m_axi_pMemPort_WLAST => mem2mat_U0_m_axi_pMemPort_WLAST,
        m_axi_pMemPort_WID => mem2mat_U0_m_axi_pMemPort_WID,
        m_axi_pMemPort_WUSER => mem2mat_U0_m_axi_pMemPort_WUSER,
        m_axi_pMemPort_ARVALID => mem2mat_U0_m_axi_pMemPort_ARVALID,
        m_axi_pMemPort_ARREADY => pMemPort_ARREADY,
        m_axi_pMemPort_ARADDR => mem2mat_U0_m_axi_pMemPort_ARADDR,
        m_axi_pMemPort_ARID => mem2mat_U0_m_axi_pMemPort_ARID,
        m_axi_pMemPort_ARLEN => mem2mat_U0_m_axi_pMemPort_ARLEN,
        m_axi_pMemPort_ARSIZE => mem2mat_U0_m_axi_pMemPort_ARSIZE,
        m_axi_pMemPort_ARBURST => mem2mat_U0_m_axi_pMemPort_ARBURST,
        m_axi_pMemPort_ARLOCK => mem2mat_U0_m_axi_pMemPort_ARLOCK,
        m_axi_pMemPort_ARCACHE => mem2mat_U0_m_axi_pMemPort_ARCACHE,
        m_axi_pMemPort_ARPROT => mem2mat_U0_m_axi_pMemPort_ARPROT,
        m_axi_pMemPort_ARQOS => mem2mat_U0_m_axi_pMemPort_ARQOS,
        m_axi_pMemPort_ARREGION => mem2mat_U0_m_axi_pMemPort_ARREGION,
        m_axi_pMemPort_ARUSER => mem2mat_U0_m_axi_pMemPort_ARUSER,
        m_axi_pMemPort_RVALID => pMemPort_RVALID,
        m_axi_pMemPort_RREADY => mem2mat_U0_m_axi_pMemPort_RREADY,
        m_axi_pMemPort_RDATA => pMemPort_RDATA,
        m_axi_pMemPort_RLAST => pMemPort_RLAST,
        m_axi_pMemPort_RID => pMemPort_RID,
        m_axi_pMemPort_RUSER => pMemPort_RUSER,
        m_axi_pMemPort_RRESP => pMemPort_RRESP,
        m_axi_pMemPort_BVALID => ap_const_logic_0,
        m_axi_pMemPort_BREADY => mem2mat_U0_m_axi_pMemPort_BREADY,
        m_axi_pMemPort_BRESP => ap_const_lv2_0,
        m_axi_pMemPort_BID => ap_const_lv1_0,
        m_axi_pMemPort_BUSER => ap_const_lv1_0,
        w_dout => indexw_c_dout,
        w_empty_n => indexw_c_empty_n,
        w_read => mem2mat_U0_w_read,
        r => mem2mat_U0_r,
        r_ap_vld => mem2mat_U0_r_ap_vld,
        img_rows_V_out_din => mem2mat_U0_img_rows_V_out_din,
        img_rows_V_out_full_n => img_rows_V_c9_full_n,
        img_rows_V_out_write => mem2mat_U0_img_rows_V_out_write,
        img_cols_V_out_din => mem2mat_U0_img_cols_V_out_din,
        img_cols_V_out_full_n => img_cols_V_c10_full_n,
        img_cols_V_out_write => mem2mat_U0_img_cols_V_out_write,
        baseAddr_address0 => mem2mat_U0_baseAddr_address0,
        baseAddr_ce0 => mem2mat_U0_baseAddr_ce0,
        baseAddr_q0 => baseAddr_q0);

    Mat2AXIvideo_U0 : component Mat2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Mat2AXIvideo_U0_ap_start,
        ap_done => Mat2AXIvideo_U0_ap_done,
        ap_continue => Mat2AXIvideo_U0_ap_continue,
        ap_idle => Mat2AXIvideo_U0_ap_idle,
        ap_ready => Mat2AXIvideo_U0_ap_ready,
        img_rows_V_dout => img_rows_V_c9_dout,
        img_rows_V_empty_n => img_rows_V_c9_empty_n,
        img_rows_V_read => Mat2AXIvideo_U0_img_rows_V_read,
        img_cols_V_dout => img_cols_V_c10_dout,
        img_cols_V_empty_n => img_cols_V_c10_empty_n,
        img_cols_V_read => Mat2AXIvideo_U0_img_cols_V_read,
        img_data_stream_0_V_dout => img_data_stream_0_V_dout,
        img_data_stream_0_V_empty_n => img_data_stream_0_V_empty_n,
        img_data_stream_0_V_read => Mat2AXIvideo_U0_img_data_stream_0_V_read,
        img_data_stream_1_V_dout => img_data_stream_1_V_dout,
        img_data_stream_1_V_empty_n => img_data_stream_1_V_empty_n,
        img_data_stream_1_V_read => Mat2AXIvideo_U0_img_data_stream_1_V_read,
        img_data_stream_2_V_dout => img_data_stream_2_V_dout,
        img_data_stream_2_V_empty_n => img_data_stream_2_V_empty_n,
        img_data_stream_2_V_read => Mat2AXIvideo_U0_img_data_stream_2_V_read,
        vstream_TDATA => Mat2AXIvideo_U0_vstream_TDATA,
        vstream_TVALID => Mat2AXIvideo_U0_vstream_TVALID,
        vstream_TREADY => vstream_TREADY,
        vstream_TKEEP => Mat2AXIvideo_U0_vstream_TKEEP,
        vstream_TSTRB => Mat2AXIvideo_U0_vstream_TSTRB,
        vstream_TUSER => Mat2AXIvideo_U0_vstream_TUSER,
        vstream_TLAST => Mat2AXIvideo_U0_vstream_TLAST,
        vstream_TID => Mat2AXIvideo_U0_vstream_TID,
        vstream_TDEST => Mat2AXIvideo_U0_vstream_TDEST);

    img_rows_V_c_U : component fifo_w32_d1_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit3_proc_U0_img_rows_V_out_din,
        if_full_n => img_rows_V_c_full_n,
        if_write => Block_Mat_exit3_proc_U0_img_rows_V_out_write,
        if_dout => img_rows_V_c_dout,
        if_empty_n => img_rows_V_c_empty_n,
        if_read => mem2mat_U0_img_rows_V_read);

    img_cols_V_c_U : component fifo_w32_d1_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit3_proc_U0_img_cols_V_out_din,
        if_full_n => img_cols_V_c_full_n,
        if_write => Block_Mat_exit3_proc_U0_img_cols_V_out_write,
        if_dout => img_cols_V_c_dout,
        if_empty_n => img_cols_V_c_empty_n,
        if_read => mem2mat_U0_img_cols_V_read);

    indexw_c_U : component fifo_w32_d1_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit3_proc_U0_indexw_out_din,
        if_full_n => indexw_c_full_n,
        if_write => Block_Mat_exit3_proc_U0_indexw_out_write,
        if_dout => indexw_c_dout,
        if_empty_n => indexw_c_empty_n,
        if_read => mem2mat_U0_w_read);

    img_data_stream_0_V_U : component fifo_w8_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => mem2mat_U0_img_data_stream_0_V_din,
        if_full_n => img_data_stream_0_V_full_n,
        if_write => mem2mat_U0_img_data_stream_0_V_write,
        if_dout => img_data_stream_0_V_dout,
        if_empty_n => img_data_stream_0_V_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_0_V_read);

    img_data_stream_1_V_U : component fifo_w8_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => mem2mat_U0_img_data_stream_1_V_din,
        if_full_n => img_data_stream_1_V_full_n,
        if_write => mem2mat_U0_img_data_stream_1_V_write,
        if_dout => img_data_stream_1_V_dout,
        if_empty_n => img_data_stream_1_V_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_1_V_read);

    img_data_stream_2_V_U : component fifo_w8_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => mem2mat_U0_img_data_stream_2_V_din,
        if_full_n => img_data_stream_2_V_full_n,
        if_write => mem2mat_U0_img_data_stream_2_V_write,
        if_dout => img_data_stream_2_V_dout,
        if_empty_n => img_data_stream_2_V_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_2_V_read);

    img_rows_V_c9_U : component fifo_w32_d1_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => mem2mat_U0_img_rows_V_out_din,
        if_full_n => img_rows_V_c9_full_n,
        if_write => mem2mat_U0_img_rows_V_out_write,
        if_dout => img_rows_V_c9_dout,
        if_empty_n => img_rows_V_c9_empty_n,
        if_read => Mat2AXIvideo_U0_img_rows_V_read);

    img_cols_V_c10_U : component fifo_w32_d1_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => mem2mat_U0_img_cols_V_out_din,
        if_full_n => img_cols_V_c10_full_n,
        if_write => mem2mat_U0_img_cols_V_out_write,
        if_dout => img_cols_V_c10_dout,
        if_empty_n => img_cols_V_c10_empty_n,
        if_read => Mat2AXIvideo_U0_img_cols_V_read);

    start_for_Mat2AXIdEe_U : component start_for_Mat2AXIdEe
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Mat2AXIvideo_U0_din,
        if_full_n => start_for_Mat2AXIvideo_U0_full_n,
        if_write => mem2mat_U0_start_write,
        if_dout => start_for_Mat2AXIvideo_U0_dout,
        if_empty_n => start_for_Mat2AXIvideo_U0_empty_n,
        if_read => Mat2AXIvideo_U0_ap_ready);





    ap_sync_reg_Block_Mat_exit3_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Block_Mat_exit3_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Block_Mat_exit3_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Block_Mat_exit3_proc_U0_ap_ready <= ap_sync_Block_Mat_exit3_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_mem2mat_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_mem2mat_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_mem2mat_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_mem2mat_U0_ap_ready <= ap_sync_mem2mat_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    Block_Mat_exit3_proc_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_sync_ready = ap_const_logic_1) and (ap_const_logic_0 = Block_Mat_exit3_proc_U0_ap_ready))) then 
                Block_Mat_exit3_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_Mat_exit3_proc_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_const_logic_1 = Block_Mat_exit3_proc_U0_ap_ready) and (ap_sync_ready = ap_const_logic_0))) then 
                Block_Mat_exit3_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_Mat_exit3_proc_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    mem2mat_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_sync_ready = ap_const_logic_1) and (mem2mat_U0_ap_ready = ap_const_logic_0))) then 
                mem2mat_U0_ap_ready_count <= std_logic_vector(unsigned(mem2mat_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((mem2mat_U0_ap_ready = ap_const_logic_1) and (ap_sync_ready = ap_const_logic_0))) then 
                mem2mat_U0_ap_ready_count <= std_logic_vector(unsigned(mem2mat_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    Block_Mat_exit3_proc_U0_ap_continue <= ap_const_logic_1;
    Block_Mat_exit3_proc_U0_ap_start <= ((ap_sync_reg_Block_Mat_exit3_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Block_Mat_exit3_proc_U0_start_full_n <= ap_const_logic_1;
    Block_Mat_exit3_proc_U0_start_write <= ap_const_logic_0;
    Mat2AXIvideo_U0_ap_continue <= ap_sync_done;
    Mat2AXIvideo_U0_ap_start <= start_for_Mat2AXIvideo_U0_empty_n;
    Mat2AXIvideo_U0_start_full_n <= ap_const_logic_1;
    Mat2AXIvideo_U0_start_write <= ap_const_logic_0;
    ap_done <= ap_sync_done;
    ap_idle <= (mem2mat_U0_ap_idle and Mat2AXIvideo_U0_ap_idle and Block_Mat_exit3_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_Block_Mat_exit3_proc_U0_ap_ready <= (ap_sync_reg_Block_Mat_exit3_proc_U0_ap_ready or Block_Mat_exit3_proc_U0_ap_ready);
    ap_sync_continue <= ap_sync_done;
    ap_sync_done <= (mem2mat_U0_ap_done and Mat2AXIvideo_U0_ap_done);
    ap_sync_mem2mat_U0_ap_ready <= (mem2mat_U0_ap_ready or ap_sync_reg_mem2mat_U0_ap_ready);
    ap_sync_ready <= (ap_sync_mem2mat_U0_ap_ready and ap_sync_Block_Mat_exit3_proc_U0_ap_ready);
    indexr <= mem2mat_U0_r;
    mem2mat_U0_ap_continue <= ap_sync_done;
    mem2mat_U0_ap_start <= ((ap_sync_reg_mem2mat_U0_ap_ready xor ap_const_logic_1) and ap_start);
    start_for_Mat2AXIvideo_U0_din <= (0=>ap_const_logic_1, others=>'-');
    vstream_TDATA <= Mat2AXIvideo_U0_vstream_TDATA;
    vstream_TDEST <= Mat2AXIvideo_U0_vstream_TDEST;
    vstream_TID <= Mat2AXIvideo_U0_vstream_TID;
    vstream_TKEEP <= Mat2AXIvideo_U0_vstream_TKEEP;
    vstream_TLAST <= Mat2AXIvideo_U0_vstream_TLAST;
    vstream_TSTRB <= Mat2AXIvideo_U0_vstream_TSTRB;
    vstream_TUSER <= Mat2AXIvideo_U0_vstream_TUSER;
    vstream_TVALID <= Mat2AXIvideo_U0_vstream_TVALID;
end behav;
